#!/bin/sh

echo "/root/moonflower/apks" > /etc/apk/repositories
cp /root/moonflower/abuild/li.mikael@gmail.com-62df97f2.rsa.pub /etc/apk/keys
apk update

apk del wun

apk add wun mesa-dri-gallium lsblk pv sfdisk gparted e2fsprogs-extra

